---
title: "lab02-balaji-veeramani.Rmd"
author: "Balaji Veeramani"
date: "February 7, 2019"
output: html_document
---

```{r}
load('nba2018-salary-points.RData')
```

```{r}
four = head(player, n = 4)
four[1]
four[0]
four[-1]
four[-c(1, 2, 3)]
four[5]
four[c(1, 2, 2, 3, 3, 3)]
```

```{r}
player[seq(2, length(player), 2)]
salary[seq(1, length(player), 2)]
team[seq(5, length(player), 5)]
scored[seq(10, length(player), 10)]
# Works if the length of player is odd
team[seq(length(player) - 1, 2, -2)]
```

```{r}
player[position == "C" & team == "GSW"]
player[team == "GSW" | team == "LAL"]
player[(position == "SG" | position == "PG") & team == "LAL"]
player[position == "SF" & (team == "GSW" | team == "LAL")]
player[which.max(salary)]
player[which.min(salary)]
player[which.max(scored)]
salary[which.max(scored)]
max(salary[position == "C"])
team[which.max(scored)]
player[which.max(points3)]
```

```{r}
gsw_scored = scored[team == "GSW"]
gsw_salary = salary[team == "GSW"]
gsw_player = player[team == "GSW"]
# Normal scale
plot(gsw_scored, gsw_salary)
text(gsw_scored, gsw_salary, labels = abbreviate(gsw_player))
# Log scale
plot(log(gsw_scored), log(gsw_salary))
text(log(gsw_scored), log(gsw_salary), labels = abbreviate(gsw_player))
```

```{r}
position_fac = factor(position)
position_fac[team == "GSW"]
position_fac[salary > 15000000]
table(position_fac[salary > 15000000])
prop.table(table(team[position_fac == "SG"]))
```

```{r}
plot(scored, salary, col = "red", pch = 18, cex = 0.8, xlab = "Points Scored", ylab = "Yearly Salary")
```
```