---
title: "lab9-balaji-veeramani"
author: "Balaji Veeramani"
date: "April 4, 2019"
output: html_document
---

```{r}
states <- rownames(USArrests)
nchar(states)
tolower(states)
toupper(states)
casefold(states)
```

```{r}
num_chars <- nchar(states)
barplot(table(num_chars))
paste(states, num_chars, sep = " = ")
paste(states[1:5], collapse = "")
substr(states, 1, 3)
substr(states, num_chars - 3, num_chars)
paste0(substr(states, 1, 2), substr(states, num_chars - 1, num_chars))
```

```{r}
states_list = list()
list_headings = c()
for(i in 4:14) {
  list_headings[i - 3] = paste(i, "chars", sep = "-")
  states_list[i - 3] = paste(states[num_chars == i], collapse = ", ")
  if (i %% 2 == 0) {
    states_list[i - 3] = toupper(states_list[i - 3])
  } else {
    states_list[i - 3] = tolower(states_list[i - 3]) 
  }
}
names(states_list) = list_headings
head(states_list)
```

```{r}
to_celsius <- function(x = 1) {
  (x - 32) * (5/9)
}

to_kelvin <- function(x = 1) {
  (x + 459.67) * (5/9)
}

to_reaumur <- function(x = 1) {
  (x - 32) * (4/9)
}

to_rankine <- function(x = 1) {
  x + 459.67
}

temp_convert <- function(x = 1, to = "celsius") {
  to = tolower(to)
  switch(to,
         "celsius" = to_celsius(x),
         "kelvin" = to_kelvin(x),
         "reaumur" = to_reaumur(x),
         "rankine" = to_rankine(x))
}

temp_convert(30, 'celsius')
temp_convert(30, 'Celsius')
temp_convert(30, 'CELSIUS')
```

```{r}
outfile <- "output.txt"

cat("---", file = outfile)
cat("\ntitle: \"Some title\"", file = outfile, append = TRUE)
cat("\nauthor: \"Your name\"", file = outfile, append = TRUE)
cat("\ndate: \"Today's date\"", file = outfile, append = TRUE)
cat("\noutput: html_document", file = outfile, append = TRUE)
cat("\n---", file = outfile, append = TRUE)
cat("\n\n", file = outfile, append = TRUE)

cat("This is the first line", file = outfile, append = TRUE)
cat("\n", file = outfile, append = TRUE)
cat("A 2nd line", file = "output.txt", append = TRUE)
cat("\n\n", file = outfile, append = TRUE)
cat("\nThe quick brown fox jumps over the lazy dog\n",
    file = outfile, append = TRUE)
```

```{r}
# your is_color() function
is_color = function(x) {
  x %in% colors()
}


# test it:
is_color('yellow')  # TRUE

is_color('blu')     # FALSE

is_color('turkuoise') # FALSE
```

```{r error=TRUE}
colplot = function(col) {
  if (!is_color(col)) {
    message = paste("invalid color", col)
    stop(message)
  }
  title = paste("Testing color", col)
  plot(rnorm(1500), rnorm(1500), col = col, main = title)
}

# this should plot
colplot('tomato')

# this stops with error message
colplot('tomate')
```
